### ISSUE TITLE
update remove liquidity UI

### ISSUE THREAD

**Issue by TzuHanLiang** [CAFECA-IO/TideBitSWAP#136]
將原本的remove liquidity UI 更新成新的樣式：

<img width="1680" alt="截圖 2021-12-13 上午11 32 56" src="https://user-images.githubusercontent.com/17249354/145748233-803b6856-a26a-4b6a-a8e1-26589358b23c.png">

新樣式：

<img width="1680" alt="截圖 2021-12-13 上午11 34 02" src="https://user-images.githubusercontent.com/17249354/145748310-b482bf1b-92c1-49f5-811e-da04475c5c11.png">

**Comment by TzuHanLiang** [comment]
1 hr

**Comment by TzuHanLiang** [comment]
take 2 hrs

**Comment by Luphia** [comment]
require linking pull request
