### ISSUE TITLE
myAsset api

### ISSUE THREAD

**Issue by Waiting4Ever** [CAFECA-IO/TideBitSWAP#140]
#113

**Comment by Waiting4Ever** [comment]
used 2 hr, remains 2 hr

**Comment by Waiting4Ever** [comment]
used 4hr, remains 3 hr

缺
getTokenDetail
getPoolDetail

**Comment by Waiting4Ever** [comment]
used 4 + 8 + 8 + 8 = 28 hours, remains 3 hours

16hours for tokenDetail
8hour for poolDetail(not done)

**Comment by Waiting4Ever** [comment]
需修改
1. interest24: 24hr swap量/ pool total supply
2. init中爬pool跟interval的步驟抽出來改成一個function

**Comment by Waiting4Ever** [comment]
需補開
1. token transactionHistory api without user address
2. pool transactionHistory api without user address
3. poolPriceChart api
4. pool 方向性參數計算price
5. tokenDetail多TVL

**Comment by TzuHanLiang** [comment]
針對token detail 畫面的補充: 
tokenDetail data 需要補加的資料如下:
1. tvl & tvl change
2. 24h trading volume & change
3. 7d trading volume
4. 24h fee
5. token's pool

token price chart api
[?] token tvl chart 
[?] token 24h trading volume chart

**Comment by TzuHanLiang** [comment]
針對pool detail 畫面的補充:
poolDetail data 需要補加的資料如下:
1. 24h fees

新增api：
[?] pool tvl chart api 
[?] pool volume chart api
[?] pool fees chart api
[?] pool liquidity chart api

**Comment by Waiting4Ever** [comment]
used 28 + 5 + 8 + 1  = 44hours,

20hours for tokenDetail
22hours for poolDetail
