### ISSUE TITLE
login at /#/assets/ will get error

### ISSUE THREAD

**Issue by TzuHanLiang** [CAFECA-IO/TideBitSWAP#184]
cause by Assets/Tokens/TokenTile => formateDecimal(token.balanceOf)

reason: 

function of formateDecimal request 2 params, which is amount and maxLength and the typeof amount need to be string. 
If typeof amount will get error

之前沒錯而現在有錯是因為，目前 lunar.getData 是壞的，try catch 後 轉用 eth_call 回傳值被我改成 number

# 再現方式

{contract: '0xDDBCB302A16f27D12Ef1cA491b4791a7b3d67c04', data: '0xad5c4648'}

ad5c4648

 const result = await this.lunar.getData({
        contract,
        data: ,
      });

**Comment by Luphia** [comment]
缺執行時間

**Comment by TzuHanLiang** [comment]
take 3hrs
