### ISSUE TITLE
remove liquidity error

### ISSUE THREAD

**Issue by TzuHanLiang** [CAFECA-IO/TideBitSWAP#185]
approve poolContract && remove liquidity will cause metamask hang住

原因： 由我這邊直接用rpc呼叫 supportedPools 改成 由 backend api 呼叫， 回傳的 pool data 中的 contract key 由 contract 改成 poolContract
在  remove liquidity 相關的部份沒有修改到所以出錯

**Comment by TzuHanLiang** [comment]
PR #183

**Comment by Luphia** [comment]
缺執行時間

**Comment by TzuHanLiang** [comment]
take 2hrs
