### ISSUE TITLE
add liquidity error: tt0/tt2 會失敗，目前原因不明

### ISSUE THREAD

**Issue by TzuHanLiang** [CAFECA-IO/TideBitSWAP#202]
經檢驗是backend reserve0， reserve1 與實際不同。

**Comment by TzuHanLiang** [comment]
需要由 wayne 那邊接續確認

**Comment by Waiting4Ever** [comment]
現有機制
1. 啟動時會問一次factory 跟db，如果db的pool跟合約上數量不一樣便會新增。
2. 為了節省啟動時間，如果db的pool沒有 reserve0 和 reserve1 ，才會去問合約取得最新的 reverse0 和 reverse1
3. 每當parser掃到mint(add liquidity), swap, burn (remove liquidity)，便會更新pool, 新增pool price, history紀錄

推測是mint與burn較晚完成，導致
1. 完成前有做過mint 或 burn，pool內容沒有更新
2. 因為db的pool有reverse0, reverse1 (舊資料)，開機檢查為了節省時間就略過同步這部分

解決辦法：
1. 進入db移除pool的reverse0, reverse1 或
2. 做一筆swap，讓parser更新pool

目前使用2. 做一筆swap，讓parser更新pool後，經過測試已經可以正常add liquidity

**Comment by Luphia** [comment]
tmp issue
