### ISSUE TITLE
add new page: pool detail

### ISSUE THREAD

**Issue by TzuHanLiang** [CAFECA-IO/TideBitSWAP#221]
- api 串接
  - 參考 issue #140 的comment
- UI reference:
<img width="1680" alt="截圖 2021-12-14 下午7 15 10" src="https://user-images.githubusercontent.com/17249354/145988167-1bca4c3b-8824-4619-af72-f8d0211eb739.png">

**Comment by TzuHanLiang** [comment]
take 4.5hrs

**Comment by Luphia** [comment]
require history list

**Comment by TzuHanLiang** [comment]
update with pr #243

> require history list
