### ISSUE TITLE
update page: token detail

### ISSUE THREAD

**Issue by TzuHanLiang** [CAFECA-IO/TideBitSWAP#222]
- api 更新
    - 參考 issue #140 的comment
- api 串接data 有誤，需要進一步確認
- UI reference： 
<img width="1680" alt="截圖 2021-12-14 下午7 18 07" src="https://user-images.githubusercontent.com/17249354/145988600-b7c75ea2-5f23-4fd9-af84-1f864f955762.png">

<img width="1680" alt="截圖 2021-12-16 下午6 01 39" src="https://user-images.githubusercontent.com/17249354/146350567-0d52b3c6-24f3-4ab1-9979-b6b5bc25c200.png">

**Comment by TzuHanLiang** [comment]
2hrs

**Comment by Luphia** [comment]
require history list

**Comment by TzuHanLiang** [comment]
> require history list

update with pr #243
