### ISSUE TITLE
poolPriceChart api

### ISSUE THREAD

**Issue by Waiting4Ever** [CAFECA-IO/TideBitSWAP#225]
- poolPriceChart api
pool 方向性參數計算price

- pool tvl chart api
- ~~pool volume chart api~~ move to #274 
- pool fees chart api
- ~~pool liquidity chart api~~ just in uniswap v3

- API wiki

**Comment by Luphia** [comment]
- zero fill
- empty data fill

**Comment by Waiting4Ever** [comment]
蠟燭圖，補間改成
x: date
y: []

**Comment by Luphia** [comment]
used 1.5 hr
remain 2 hrs

**Comment by Waiting4Ever** [comment]
pool volume chart api depend on #259

**Comment by Waiting4Ever** [comment]
used 3.5 hrs
