### ISSUE TITLE
token chart api

### ISSUE THREAD

**Issue by Waiting4Ever** [CAFECA-IO/TideBitSWAP#228]
- token price chart api
- token tvl chart api
- ~~token 24h trading volume chart api~~ move to #274 

- API wiki

**Comment by Waiting4Ever** [comment]
tokenPrice拿錯了
應該要拿token_price table，然後同poolprice補間

**Comment by Luphia** [comment]
- zero fill
- empty data fill

**Comment by Waiting4Ever** [comment]
poolprice 補間改成
x: date
y: []

**Comment by Waiting4Ever** [comment]
used 2hrs
~~remain 2hrs~~ because token 24h trading volume chart api doesn't need to finish in this issue

**Comment by Waiting4Ever** [comment]
token 24h trading volume chart api depend on 259

**Comment by Waiting4Ever** [comment]
used 2hrs
