### ISSUE TITLE
Swap to exact amount

### ISSUE THREAD

**Issue by Luphia** [CAFECA-IO/TideBitSWAP#235]
Call these functions if user input the out amount:
- swapTokensForExactETH
- swapETHForExactTokens
- swapTokensForExactTokens

**Comment by TzuHanLiang** [comment]
- https://ropsten.etherscan.io/tx/0x4891132c6417a749d82a2efd842419e68b1af7c4680ac4d4a864d6e321cc1e43

**Comment by TzuHanLiang** [comment]
- summary required update

**Comment by TzuHanLiang** [comment]
- take 4hrs , repair need another hour
