### ISSUE TITLE
Alter Table

### ISSUE THREAD

**Issue by Waiting4Ever** [CAFECA-IO/TideBitSWAP#259]
## migration流程
1. _migration()
2. 讀取database/migrations資料夾底下所有檔案名稱 -> dirMigrations
3. 讀取db.migrations table內所有資料 -> dbMigrations
4. filter 出新加入的dirMigrations 的檔名 -> newMigrations
5. 迴圈執行
  5-1. 執行up function，印出執行內容
  5-2. insert migration table

## migration檔名
```
YYYYMMDDhhmmss-your-operation.js

# 20211222103600-overview-add-VolumeToday.js
```

## 新增檔案
- backend/database/sqlType.js
- backend/database/entity/MigrationsDao.js

### sqlite3/index
- async _runMigration()
- parseAttribute(attr)
- async createTable(tableName, attributes)
- async addColumn(tableName, columnName, attribute)
- async removeColumn(tableName, columnName)

**Comment by Luphia** [comment]
Requirement:
1. Table version schema in [WIKI](https://github.com/CAFECA-IO/TideBitSWAP/wiki/Database-Schema)
2. Latest version list in [WIKI](https://github.com/CAFECA-IO/TideBitSWAP/wiki/Database-Schema)

**Comment by Luphia** [comment]
- something wrong

**Comment by Waiting4Ever** [comment]
used 8 hr
remain 8 hr

由於product環境npm install 出錯，revert #260 
改由自己寫migrate

**Comment by Waiting4Ever** [comment]
use 10 hrs
remain 6hrs

**Comment by Luphia** [comment]
- complete [document](https://github.com/CAFECA-IO/TideBitSWAP/wiki/Database-migration)

**Comment by Luphia** [comment]
- bug happened

![截圖 2021-12-24 下午11 00 17](https://user-images.githubusercontent.com/270062/147360782-fe4ab3bf-1250-414c-ac62-6ff083cebb7d.png)

**Comment by Waiting4Ever** [comment]
new migrations used 10 hrs

this ticket totally used 18 hrs
