### ISSUE TITLE
Parse User Asset Composition

### ISSUE THREAD

**Issue by TzuHanLiang** [CAFECA-IO/TideBitSWAP#28]
某使用者有哪些token，個別token在在鏈上的數量，及在pool裡的數量

1. update display ui - 1hr
2. fetch asset detail - 2hr
3. parse data
    3.1 get asset balance in token contract & pool contract
    3.2 get distribution
    3.3 get allocation
<img width="359" alt="截圖 2021-10-13 下午3 41 42" src="https://user-images.githubusercontent.com/17249354/137088929-e07f3f63-aa06-47dc-b3c8-7833b573c3e4.png">
數量

**Comment by Luphia** [comment]
used 5 hrs
