### ISSUE TITLE
PRICE 24H display

### ISSUE THREAD

**Issue by Luphia** [CAFECA-IO/TideBitSWAP#288]
- My Assets: Tokens
- PRICE 24H is 1% of the real number（99.99% -> 0.9999%）

<img width="940" alt="截圖 2021-12-24 上午11 56 37" src="https://user-images.githubusercontent.com/270062/147314502-0adeaadc-1ce9-4c86-bd1b-0aed5f7c6324.png">

**Comment by TzuHanLiang** [comment]
take 1hr
