### ISSUE TITLE
Get Pools' Detail - Survey

### ISSUE THREAD

**Issue by Luphia** [CAFECA-IO/TideBitSWAP#30]
## calculate share
pair token total supply = ptts
token A balanceOf pair contract = taB
deposit token A amount = dtaA
share = dtaA / taB * ptts

## calculate yield
~yield~

**Comment by TzuHanLiang** [comment]
#Reference:
[Understanding Returns](https://docs.uniswap.org/protocol/V2/concepts/advanced-topics/understanding-returns)

[Losses to LPs(Liquidity Providers) due to price variation](https://pintail.medium.com/uniswap-a-good-deal-for-liquidity-providers-104c0b6816f2)

實際使用時間：2h

**Comment by TzuHanLiang** [comment]
share = dtaA / taB 應該是percentage
shareAmount = share  * ptts
