### ISSUE TITLE
Add Stake UI

### ISSUE THREAD

**Issue by TzuHanLiang** [CAFECA-IO/TideBitSWAP#302]
![截圖 2021-12-28 上午10 10 09](https://user-images.githubusercontent.com/17249354/147520014-6c036c6b-c047-4039-a3f0-1ab5b99dee48.png)
![截圖 2021-12-28 上午10 13 26](https://user-images.githubusercontent.com/17249354/147520226-777935a7-d9b8-4f7c-a265-63f2bc79626f.png)
![截圖 2021-12-28 上午10 10 39](https://user-images.githubusercontent.com/17249354/147520041-f4e785bb-3612-4f07-bfcf-e6652959695e.png)
![截圖 2021-12-28 上午10 11 37](https://user-images.githubusercontent.com/17249354/147520099-d5f36be2-e417-46a7-9244-62a27d7251c3.png)
![截圖 2021-12-28 上午10 13 53](https://user-images.githubusercontent.com/17249354/147520252-efe1a279-850c-4837-9572-3e32569631ef.png)

- DropDownTile 2 size:  5 points
- ROI caculator:  5 points

**Comment by Luphia** [comment]
<img width="1292" alt="ScreenShot" src="https://user-images.githubusercontent.com/270062/147527403-cd6aa02c-dab6-4f6c-839a-3d38caca50ba.png">

支持過濾條件：該帳戶是否 staked， 正在發放股息。
支持排序：熱度/年化利率/獎勵比例/未收取獎勵數量/流動性池總量（折算為美元）
支持搜尋：主要是 Pool 兩個 token 名字

**Comment by Luphia** [comment]
![image](https://user-images.githubusercontent.com/270062/147533993-55292e71-e4ce-4605-855e-fb7322686264.png)

**Comment by TzuHanLiang** [comment]
- finish filter & sorting function
- finish navigation
- finish mockup data
- finish data update logic

take 6 hrs

**Comment by TzuHanLiang** [comment]
remain 6hrs

**Comment by TzuHanLiang** [comment]
take 7 hrs, remain 3hrs

- 低估 component 的數量

**Comment by TzuHanLiang** [comment]
take 3hrs， remain 0hr

- 完成：
  - Stake UI
  - Stake UI logic

- 預估時間與實際操作時間差距：
  - 沒有評估到畫面邏輯的時間
