### ISSUE TITLE
Overview Charts display error with large amount

### ISSUE THREAD

**Issue by Luphia** [CAFECA-IO/TideBitSWAP#312]
55.48st display lower than 2.264

<img width="928" alt="截圖 2021-12-29 下午6 52 17" src="https://user-images.githubusercontent.com/270062/147655473-c782a4a4-d84d-4dfe-a33d-561690af1af0.png">

**Comment by TzuHanLiang** [comment]
初步判斷 code 邏輯 沒有問題，需要套用遠端伺服器的資料去確認問題。

- 套用遠端伺服器預計需要 1hr
- 重新檢查 code 邏輯需要 1hr

**Comment by TzuHanLiang** [comment]
- take 1hr
