### ISSUE TITLE
Stake: 串接 contract

### ISSUE THREAD

**Issue by TzuHanLiang** [CAFECA-IO/TideBitSWAP#313]
需要串接 6 function：
- userInfo
- pendingReward
- approve
- allowance
- deposit
- withdraw

// for testing will need another 2  function, because backend is not ready

- stakedToken()
- rewardToken()

**Comment by Luphia** [comment]
<img width="1085" alt="Screen Shot 2022-01-05 at 9 44 55 AM" src="https://user-images.githubusercontent.com/270062/148150312-c479afd9-6086-4959-9cb0-812126ecad2e.png">

**Comment by Luphia** [comment]
<img width="337" alt="Screen Shot 2022-01-05 at 9 45 06 AM" src="https://user-images.githubusercontent.com/270062/148150346-8cb9e6d3-c45c-4c48-978b-e92d0939019e.png">

**Comment by Luphia** [comment]
<img width="1048" alt="Screen Shot 2022-01-05 at 9 46 11 AM" src="https://user-images.githubusercontent.com/270062/148150424-4afcc92a-2fdc-4378-9116-1d1d81a8622a.png">
<img width="1054" alt="Screen Shot 2022-01-05 at 9 46 56 AM" src="https://user-images.githubusercontent.com/270062/148150438-70d98609-c995-4c96-ab27-7acc116c8cf0.png">
<img width="1049" alt="Screen Shot 2022-01-05 at 9 51 15 AM" src="https://user-images.githubusercontent.com/270062/148150465-8bbdb41d-39dd-4ed5-bf1a-db5a5d911e0e.png">

**Comment by Luphia** [comment]
<img width="322" alt="Screen Shot 2022-01-05 at 9 58 18 AM" src="https://user-images.githubusercontent.com/270062/148153884-d61817a3-9f50-4794-bf32-cfd7699eb5b7.png">

**Comment by TzuHanLiang** [comment]
take 8hr:

- 1/5 3hr
- 1/6 5hr
- with new harvest dialog
- with filter options: isLive and already staked
- with function poolLimitPerUser
