### ISSUE TITLE
Staking API Format and Document

### ISSUE THREAD

**Issue by Luphia** [CAFECA-IO/TideBitSWAP#327]
- Design for [Stakes](https://swap.tidebit.network/#/stakes)

**Comment by Waiting4Ever** [comment]
need survey 1hr

**Comment by Waiting4Ever** [comment]
https://github.com/CAFECA-IO/TideBitSWAP/wiki/backend-API-v1#24-stake-list

**Comment by Waiting4Ever** [comment]
used 1.5hr
