### ISSUE TITLE
tokenDetail: internal server error

### ISSUE THREAD

**Issue by TzuHanLiang** [CAFECA-IO/TideBitSWAP#351]
occurs in require tokenDetail on binance mainnet

example:
- /api/v1/chainId/0x38/explorer/tokenDetail/0x0e09fabb73bd3ade0a17ecc321fd13a19e81ce82
- /api/v1/chainId/0x38/explorer/tokenDetail/0x6b23c89196deb721e6fd9726e6c76e4810a464bc

**Comment by Waiting4Ever** [comment]
used 1.5 hrs
