### ISSUE TITLE
TideBit SWAP Layout V3 - 1

### ISSUE THREAD

**Issue by TzuHanLiang** [CAFECA-IO/TideBitSWAP#62]
Before Login: 
1個頁面，2張圖表(Liquidity & Volume)，3個列表(pairs & currencies & transactions)

How is going on with this exchange
Total liquidity in exchange
Total trading volumn in 24 hrs
What is the most popular currency, how is the price and volumn
What is the most traded currency pairs, how is the price and volumn
Is there anyone else using the exchange to trade

**Comment by TzuHanLiang** [comment]
1. 補上按下側邊欄 pools  及 tokens 的畫面
2. 名称修改 
    1. pools —> pairs
    2. Dashboard —> my assets
3. swap pannel 交易对与summary 从左右分布改为上下分布
4. 新增swap summary 要呈现的细节
    1. fee
    2. slippage
    3. minimum
5. 补上earn 的画面 —> provide/ take liquidity pannel
    1. 样式与 swap pannel 一致 左边为 交易pannel 右边为 pool list 主要需要呈现yield & myShare
    2. liquidity pannel的交易对与summary一样要以垂直方向排列
6. 侧边栏样式调整
    1. 參考路飛會議上分享的樣式

**Comment by Luphia** [comment]
used 6 hrs
