### ISSUE TITLE
TideBit SWAP Layout V3 - 2

### ISSUE THREAD

**Issue by TzuHanLiang** [CAFECA-IO/TideBitSWAP#63]
After Login:  --> Dashboard Design:
What network can I use with this exchange
What currencies do I have
Can I add more currencies
What can I trade with, and how does it cost
Can I earn passive income with this exchange, and what is the amount of internal rate of return
I do not have enough ETH, how can I buy some

**Comment by Luphia** [comment]
used 6 hrs
