### ISSUE TITLE
UI - Swap

### ISSUE THREAD

**Issue by TzuHanLiang** [CAFECA-IO/TideBitSWAP#71]
1. Css Style Update 3hr
        1. 重新設計 1.5hr
        2. 實作 1.5hr 
    2. 交易各式修改 3hr
        1. Swap with two pairs (TTA -> WETH -> TTC)
    3. 交易過後更新資料 1.5hr

**Comment by Luphia** [comment]
- candlestick chart remain 3 hrs

**Comment by Luphia** [comment]
remain 5 hrs (used 3 hrs)

**Comment by Luphia** [comment]
remain 1.5 hr (used 4.5 hrs)

**Comment by TzuHanLiang** [comment]
connect with issue #102 ， 超出的時間是卡在candle stick chart， 後來以更換library解決

**Comment by Luphia** [comment]
used 9 hrs
