### ISSUE TITLE
UI - Invest

### ISSUE THREAD

**Issue by TzuHanLiang** [CAFECA-IO/TideBitSWAP#72]
1. Earn 4.5hr
    1. 交易格式更新 3hr
    2. 交易過後更新資料 1.5hr
 combined with #73

**Comment by Luphia** [comment]
remain 3 hrs (used 3 hrs)

**Comment by Luphia** [comment]
- remain transaction, import token
remain 3 hrs (used 3 hrs)

**Comment by Luphia** [comment]
remain 1.5 hr (used 1.5 hr)

**Comment by TzuHanLiang** [comment]
used 6 hrs
