### ISSUE TITLE
TideBit Swap ETH Operation

### ISSUE THREAD

**Issue by Luphia** [CAFECA-IO/TideBitSWAP#73]
- Find [WETH](https://ropsten.etherscan.io/address/0xddbcb302a16f27d12ef1ca491b4791a7b3d67c04#readContract) address
- No need to create pool with token and WETH
- [Add liquidity with ETH](https://ropsten.etherscan.io/tx/0xc6e39e42d6a58a1ae9f09d0ea2fef13ee7c0d8b3206419335317eb2d45a4c67f)
- [Swap with two pairs](https://ropsten.etherscan.io/tx/0xba1e80eb5fbc6330e9b3221231c7140402acd6eb7dfa8b93108d822366e9cefd) (TTA -> WETH -> TTC)
- [Remove liquidity](https://ropsten.etherscan.io/tx/0x250884ca0c3951b4ad841dd79436d79be388be53acd8974375500f3d0fa74124)

**Comment by TzuHanLiang** [comment]
2 hrs
